[server]
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#3b82f6"
backgroundColor = "#0b141c"
secondaryBackgroundColor = "#141c24"
textColor = "#dae3ee"
borderColor = "#222f3d"
font = "sans-serif"
codeFont = "JetBrains Mono"
